[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
anyhow = "1.0.71"
thiserror="1.0.43"
clap = {version = "4.3.19", features=["derive"]}
structopt = "0.3.26"
